def get_heuristics(MetricsInterface):
    arc_restart = MetricsInterface.getOutputContainer()['Number of times user had to restart an arc'].value
    cur_score = MetricsInterface.getOutputContainer()['Current path score'].value
    tot_out_path = MetricsInterface.getOutputContainer()['Total time out of path'].value
    tot_pat_tim = MetricsInterface.getOutputContainer()['Total path time'].value
    cur_pat_tim = MetricsInterface.getOutputContainer()['Current path time'].value
    avg_tim_pat = MetricsInterface.getOutputContainer()['Average time per path'].value
    avg_sco_pat = MetricsInterface.getOutputContainer()['Average score per path'].value
    cur_pat_out_time = MetricsInterface.getOutputContainer()['Current path time out of range'].value
    avg_pat_out_time = MetricsInterface.getOutputContainer()['Average time out of path range'].value
    ball_knock = MetricsInterface.getOutputContainer()['Number of tennis balls knocked over by operator'].value
    pole_touch = MetricsInterface.getOutputContainer()['Number of poles touched'].value
    pole_fell = MetricsInterface.getOutputContainer()['Number of poles that fell over'].value
    barr_touch = MetricsInterface.getOutputContainer()['Number of barrels touches'].value
    barr_knock = MetricsInterface.getOutputContainer()['Number of barrels knocked over'].value
    equip_coll = MetricsInterface.getOutputContainer()['Number of equipment collisions'].value
    num_idle = MetricsInterface.getOutputContainer()['Number of times machine was left idling'].value
    buck_self = MetricsInterface.getOutputContainer()['Bucket Self Contact'].value
    rat_idle = MetricsInterface.getOutputContainer()['Ratio of time that operator runs equipment vs idle time'].value
    coll_env = MetricsInterface.getOutputContainer()['Collisions with environment'].value
    num_goal = MetricsInterface.getOutputContainer()['Exercise Number of goals met'].value
    ex_time = MetricsInterface.getOutputContainer()['Exercise Time'].value
    buck_truck = MetricsInterface.getOutputContainer()['Safety violation bucket over truck cab'].value
    dump_truck = MetricsInterface.getOutputContainer()['Safety violation dump truck contact'].value
    elec_line = MetricsInterface.getOutputContainer()['Safety violation electrical lines'].value
    hum_cont = MetricsInterface.getOutputContainer()['Safety violation human contact'].value
    load_hum = MetricsInterface.getOutputContainer()['Safety violation load over human'].value
    park_pos = MetricsInterface.getOutputContainer()['Safety violation unsafe parking position'].value
    flip_vehc = MetricsInterface.getOutputContainer()['Safety violation Flipped Vehicle'].value
